### ISSUE TITLE
Error Redis

### ISSUE THREAD

**Issue by Rhayeksa** [kmrifat/django_chat#5]
# Error Redis
![image](https://github.com/kmrifat/django_chat/assets/53942184/9647f09d-bf70-4a93-82e0-9482d8d96320)

Can help me...?

**Comment by Pankajsangale16** [comment]
Yes

**Comment by Pankajsangale16** [comment]
WhatsApp Me on 7517517212

**Comment by Pankajsangale16** [comment]
Great!
